// ============================================================
// ASHENMOOR — card database (all game content is data)
// ============================================================
export const artPath = (id) => `./assets/art/${id}.jpg`;

export const HEROES = {
  kaelen: {
    id: "kaelen",
    name: "Kaelen Dray",
    title: "The Ashblade",
    color: "ember",
    hp: 12, atk: 2, thw: 1, def: 2, handSize: 5,
    art: "hero_kaelen",
    ability: {
      name: "Emberheart",
      text: "Free, once per round: deal 1 damage to an enemy.",
      kind: "dmg1",
    },
    flavor: "He swore his oath on a burning city.",
    deck: [
      "ember_slash", "ember_slash", "ember_slash",
      "cleaving_arc", "cleaving_arc",
      "battle_fury", "battle_fury",
      "second_wind", "second_wind",
      "bulwark", "bulwark",
      "reckless_charge", "reckless_charge",
      "rallying_cry", "rallying_cry",
      "ashen_duelist", "ashen_duelist",
      "cinder_hound", "cinder_hound",
      "emberbrand", "emberbrand",
      "wardplate",
      "stagger", "stagger",
      "wardens_beacon", "wardens_beacon",
      "wardens_resolve", "wardens_resolve", "wardens_resolve",
    ],
  },
  sera: {
    id: "sera",
    name: "Sera Voss",
    title: "Riftweaver",
    color: "rift",
    hp: 11, atk: 1, thw: 2, def: 2, handSize: 6,
    art: "hero_sera",
    ability: {
      name: "Riftsight",
      text: "Free, once per round: remove 1 doom from the scheme.",
      kind: "thw1",
    },
    flavor: "She has seen how the story ends. She disagrees.",
    deck: [
      "rift_bolt", "rift_bolt", "rift_bolt",
      "unravel", "unravel", "unravel",
      "veil_of_mist", "veil_of_mist",
      "foresight", "foresight",
      "banish", "banish",
      "temporal_slip", "temporal_slip",
      "apprentice_scryer", "apprentice_scryer",
      "sentinel_golem", "sentinel_golem",
      "focus_crystal", "focus_crystal",
      "sigil_of_clarity", "sigil_of_clarity",
      "hex_of_cinders", "hex_of_cinders",
      "wardens_beacon", "wardens_beacon",
      "wardens_resolve", "wardens_resolve", "wardens_resolve",
    ],
  },
  odran: {
    id: "odran",
    name: "Odran Vael",
    title: "The Gravewarden",
    color: "aegis",
    hp: 14, atk: 1, thw: 2, def: 3, handSize: 5,
    art: "hero_odran",
    ability: {
      name: "Aegis",
      text: "Free, once per round: gain 1 shield.",
      kind: "shield1",
    },
    flavor: "The dead of Ashenmoor sleep because he does not.",
    deck: [
      "shield_wall", "shield_wall", "shield_wall",
      "verdict", "verdict", "verdict",
      "rally_the_watch", "rally_the_watch",
      "stand_fast", "stand_fast", "stand_fast",
      "lantern_bearer", "lantern_bearer",
      "watch_captain", "watch_captain",
      "stone_sentry", "stone_sentry",
      "aegis_plate",
      "vigil_banner", "vigil_banner",
      "last_bastion", "last_bastion",
      "judgment_bell", "judgment_bell",
      "wardens_beacon", "wardens_beacon",
      "wardens_resolve", "wardens_resolve", "wardens_resolve",
    ],
  },
};

// type: event | ally | upgrade | resource
// res: value when discarded to pay a cost (default 1)
// effect/enter targets: "enemy" (villain or minion) | "minion" | none
export const CARDS = {
  // ---- Kaelen (ember) ----
  ember_slash: {
    name: "Ember Slash", type: "event", cost: 1, faction: "kaelen",
    text: "Deal 3 damage to an enemy.",
    flavor: "The blade remembers the fire.",
    effect: { dmg: 3, target: "enemy" },
  },
  cleaving_arc: {
    name: "Cleaving Arc", type: "event", cost: 3, faction: "kaelen",
    text: "Deal 2 damage to the villain and each minion.",
    flavor: "One horizon of flame.",
    effect: { dmgAll: 2 },
  },
  battle_fury: {
    name: "Battle Fury", type: "event", cost: 1, faction: "kaelen",
    text: "Ready your hero.",
    flavor: "Rage is a second wind with teeth.",
    effect: { readyHero: true },
  },
  second_wind: {
    name: "Second Wind", type: "event", cost: 1, faction: "kaelen",
    text: "Heal 3 damage from your hero.",
    flavor: "Stand. The city still needs you.",
    effect: { heal: 3 },
  },
  bulwark: {
    name: "Bulwark", type: "event", cost: 1, faction: "kaelen",
    text: "Gain 3 shield until your next turn.",
    flavor: "The wall holds because he is the wall.",
    effect: { shield: 3 },
  },
  reckless_charge: {
    name: "Reckless Charge", type: "event", cost: 0, faction: "kaelen",
    text: "Deal 2 damage to an enemy. Your hero suffers 1 damage.",
    flavor: "Caution died at the gates.",
    effect: { dmg: 2, target: "enemy", selfDmg: 1 },
  },
  rallying_cry: {
    name: "Rallying Cry", type: "event", cost: 2, faction: "kaelen",
    text: "Draw 2 cards.",
    flavor: "Ashenmoor answers.",
    effect: { draw: 2 },
  },
  ashen_duelist: {
    name: "Ashen Duelist", type: "ally", cost: 2, faction: "kaelen",
    atk: 2, thw: 1, hp: 3,
    text: "Ally. May Attack or Disrupt once per round, then suffers 1 damage.",
    flavor: "Two blades, no promises.",
  },
  cinder_hound: {
    name: "Cinder Hound", type: "ally", cost: 1, faction: "kaelen",
    atk: 1, thw: 0, hp: 2,
    text: "Ally. Enters play: deal 1 damage to an enemy.",
    flavor: "Loyal to the last spark.",
    enter: { dmg: 1, target: "enemy" },
  },
  emberbrand: {
    name: "Emberbrand", type: "upgrade", cost: 2, faction: "kaelen",
    text: "Your hero's basic Attack deals +1 damage.",
    flavor: "Forged in the ruin it avenges.",
    mod: { atk: 1 },
  },
  wardplate: {
    name: "Wardplate", type: "upgrade", cost: 1, faction: "kaelen",
    text: "Your hero has +1 DEF.",
    flavor: "Dented, never broken.",
    mod: { def: 1 },
  },
  // ---- Sera (rift) ----
  rift_bolt: {
    name: "Rift Bolt", type: "event", cost: 1, faction: "sera",
    text: "Deal 3 damage to an enemy.",
    flavor: "The Void bites both ways.",
    effect: { dmg: 3, target: "enemy" },
  },
  unravel: {
    name: "Unravel", type: "event", cost: 1, faction: "sera",
    text: "Remove 2 doom from the scheme.",
    flavor: "Every curse is a knot.",
    effect: { thwart: 2 },
  },
  veil_of_mist: {
    name: "Veil of Mist", type: "event", cost: 1, faction: "sera",
    text: "Gain 3 shield until your next turn.",
    flavor: "What the eye loses, the blade cannot find.",
    effect: { shield: 3 },
  },
  foresight: {
    name: "Foresight", type: "event", cost: 1, faction: "sera",
    text: "Draw 2 cards.",
    flavor: "She read tomorrow's chronicle.",
    effect: { draw: 2 },
  },
  banish: {
    name: "Banish", type: "event", cost: 2, faction: "sera",
    text: "Defeat a minion.",
    flavor: "Go back to the dark that made you.",
    effect: { banish: true, target: "minion" },
  },
  temporal_slip: {
    name: "Temporal Slip", type: "event", cost: 2, faction: "sera",
    text: "The villain does not activate during the next villain phase.",
    flavor: "A second, stolen twice.",
    effect: { seal: true },
  },
  apprentice_scryer: {
    name: "Apprentice Scryer", type: "ally", cost: 1, faction: "sera",
    atk: 1, thw: 1, hp: 1,
    text: "Ally. Enters play: draw 1 card.",
    flavor: "She sees more than she says.",
    enter: { draw: 1 },
  },
  sentinel_golem: {
    name: "Sentinel Golem", type: "ally", cost: 3, faction: "sera",
    atk: 1, thw: 1, hp: 5,
    text: "Ally. A patient wall of stone and crystal.",
    flavor: "It does not tire. It does not yield.",
  },
  focus_crystal: {
    name: "Focus Crystal", type: "upgrade", cost: 2, faction: "sera",
    text: "The first card you play each round costs 1 less.",
    flavor: "Clarity, cut and polished.",
    mod: { discount: 1 },
  },
  sigil_of_clarity: {
    name: "Sigil of Clarity", type: "upgrade", cost: 1, faction: "sera",
    text: "Your hero's Disrupt removes +1 doom.",
    flavor: "Truth, drawn in light.",
    mod: { thw: 1 },
  },
  // ---- Odran (aegis) ----
  shield_wall: {
    name: "Shield Wall", type: "event", cost: 1, faction: "odran",
    text: "Gain 2 shield. Draw 1 card.",
    flavor: "Stone breaks. The Watch does not.",
    effect: { shield: 2, draw: 1 },
  },
  verdict: {
    name: "Verdict", type: "event", cost: 2, faction: "odran",
    text: "Deal 2 damage to an enemy. Gain 2 shield.",
    flavor: "Judgment, delivered in gold.",
    effect: { dmg: 2, target: "enemy", shield: 2 },
  },
  rally_the_watch: {
    name: "Rally the Watch", type: "event", cost: 2, faction: "odran",
    text: "Ready all your allies.",
    flavor: "The bell rings once. It is enough.",
    effect: { readyAllies: true },
  },
  stand_fast: {
    name: "Stand Fast", type: "event", cost: 1, faction: "odran",
    text: "Ready your hero. Gain 1 shield.",
    flavor: "One more hour. Then one more.",
    effect: { readyHero: true, shield: 1 },
  },
  lantern_bearer: {
    name: "Lantern Bearer", type: "ally", cost: 1, faction: "odran",
    atk: 1, thw: 1, hp: 2,
    text: "Ally. Enters play: heal 1 damage from your hero.",
    flavor: "The dark counts her candle first.",
    enter: { heal: 1 },
  },
  watch_captain: {
    name: "Watch Captain", type: "ally", cost: 2, faction: "odran",
    atk: 1, thw: 1, hp: 3,
    text: "Ally. Enters play: gain 2 shield.",
    flavor: "Thirty years on the wall. Zero breaches.",
    enter: { shield: 2 },
  },
  stone_sentry: {
    name: "Stone Sentry", type: "ally", cost: 3, faction: "odran",
    atk: 2, thw: 0, hp: 5,
    text: "Ally. A tireless wall of consecrated stone.",
    flavor: "It remembers every oath carved into it.",
  },
  aegis_plate: {
    name: "Aegis Plate", type: "upgrade", cost: 2, faction: "odran",
    text: "Your hero has +1 DEF.",
    flavor: "Worn by seven wardens. Failed none.",
    mod: { def: 1 },
  },
  vigil_banner: {
    name: "Vigil Banner", type: "upgrade", cost: 2, faction: "odran",
    text: "Your allies' Attack +1.",
    flavor: "Where it stands, the Watch holds.",
    mod: { allyAtk: 1 },
  },
  last_bastion: {
    name: "Last Bastion", type: "event", cost: 3, faction: "odran",
    text: "Heal 4 damage. Remove 2 doom from the scheme.",
    flavor: "When all else falls, he is the wall.",
    effect: { heal: 4, thwart: 2 },
  },
  // ---- v1.3 status & scheme tech ----
  stagger: {
    name: "Stagger", type: "event", cost: 2, faction: "kaelen",
    text: "Deal 1 damage to the villain and Stun him — he skips his next ATTACK.",
    flavor: "Even a hollow crown rings when struck.",
    effect: { dmgVillain: 1, stun: 1 },
  },
  hex_of_cinders: {
    name: "Hex of Cinders", type: "event", cost: 1, faction: "sera",
    text: "Burn 2 — at the start of each villain phase, the villain takes 1 damage and 1 Burn fades.",
    flavor: "A slow fire reads no petitions.",
    effect: { burn: 2 },
  },
  judgment_bell: {
    name: "Judgment Bell", type: "event", cost: 2, faction: "odran",
    text: "Remove 2 doom from a scheme. Draw 1 card.",
    flavor: "When it tolls, even the Spire listens.",
    effect: { thwart: 2, draw: 1 },
  },
  // ---- campaign relics (neutral, earned in The Long Vigil) ----
  cinder_of_the_first_flame: {
    name: "Cinder of the First Flame", type: "event", cost: 1, faction: "neutral",
    text: "Deal 4 damage to an enemy.",
    flavor: "Older than the dark. Angrier, too.",
    effect: { dmg: 4, target: "enemy" },
  },
  wardens_oath: {
    name: "The Warden's Oath", type: "upgrade", cost: 3, faction: "neutral",
    text: "Your hero's ability may be used twice each round.",
    flavor: "Sworn once. Kept forever.",
    mod: { abilityCharges: 1 },
  },
  shard_of_the_spire: {
    name: "Shard of the Spire", type: "resource", cost: null, faction: "neutral",
    res: 3,
    text: "Cannot be played. Worth 3 when paying costs.",
    flavor: "It still hums with the Heart's pulse.",
  },
  // ---- shared ----
  wardens_beacon: {
    name: "Warden's Beacon", type: "event", cost: 1, faction: "neutral",
    text: "Remove 2 doom from a scheme.",
    flavor: "One light, held against the tide.",
    effect: { thwart: 2 },
  },
  wardens_resolve: {
    name: "Warden's Resolve", type: "resource", cost: null, faction: "neutral",
    res: 2,
    text: "Cannot be played. Worth 2 when paying costs.",
    flavor: "The oath outlasts the arm that swore it.",
  },
};

// ---- encounter set: The Hollow Court ----
export const ENCOUNTERS = {
  void_cultist: {
    name: "Void Cultist", type: "minion", atk: 1, hp: 2, boost: 1,
    text: "Spawn: place 1 doom on the scheme.",
    flavor: "He gave his name away first.",
    spawn: { threat: 1 },
  },
  hollow_beast: {
    name: "Hollow Beast", type: "minion", atk: 3, hp: 4, boost: 2, guard: true,
    text: "Guard — while it lives, the villain cannot be attacked.",
    flavor: "Its ribs cage nothing but night.",
  },
  rift_stalker: {
    name: "Rift Stalker", type: "minion", atk: 2, hp: 3, boost: 1,
    text: "Quickstrike — attacks immediately when it spawns.",
    flavor: "It arrives claws-first.",
    quickstrike: true,
  },
  creeping_despair: {
    name: "Creeping Despair", type: "treachery", boost: 2,
    text: "Place 2 doom on the scheme.",
    flavor: "Hope goes out like candles.",
    fx: { threat: 2 },
  },
  void_lash: {
    name: "Void Lash", type: "treachery", boost: 1,
    text: "The villain immediately attacks you.",
    flavor: "The dark has a long arm.",
    fx: { villainAttack: true },
  },
  shattered_nerves: {
    name: "Shattered Nerves", type: "treachery", boost: 1,
    text: "Discard 2 random cards from your hand.",
    flavor: "The mind breaks quieter than glass.",
    fx: { discardRandom: 2 },
  },
  feast_of_shadows: {
    name: "Feast of Shadows", type: "treachery", boost: 1,
    text: "The villain heals 3. If already unharmed, place 1 doom instead.",
    flavor: "He drinks what the city forgets.",
    fx: { healVillain: 3 },
  },
  whispers_of_the_spire: {
    name: "Whispers of the Spire", type: "treachery", boost: 2,
    text: "Exhaust your hero. If already exhausted, place 1 doom instead.",
    flavor: "They know your name. They keep saying it.",
    fx: { exhaustHero: true },
  },
  crown_of_echoes: {
    name: "Crown of Echoes", type: "attachment", boost: 2,
    text: "Attach to the villain. His SCHEME places +1 doom.",
    flavor: "Every echo is an order.",
    mod: { sch: 1 },
  },
  void_edge: {
    name: "Void Edge", type: "attachment", boost: 2,
    text: "Attach to the villain. His ATTACK deals +1 damage.",
    flavor: "It cuts the light out of things.",
    mod: { atk: 1 },
  },
  // ---- Vexahl's set ----
  chant_of_hollowing: {
    name: "Chant of Hollowing", type: "treachery", boost: 2,
    text: "Place 1 doom, plus 1 for each minion in play.",
    flavor: "The song needs singers.",
    fx: { threatBase: 1, threatPerMinion: 1 },
  },
  silvered_tongue: {
    name: "Silvered Tongue", type: "treachery", boost: 1,
    text: "Exhaust a random ready ally. If none, place 2 doom.",
    flavor: "It only ever asks for a moment.",
    fx: { exhaustAlly: true },
  },
  herald_of_the_spire: {
    name: "Herald of the Spire", type: "minion", atk: 1, hp: 4, boost: 1, guard: true,
    text: "Guard — while it lives, the villain cannot be attacked. Spawn: place 1 doom.",
    flavor: "Its proclamations are always true. Eventually.",
    spawn: { threat: 1 },
  },
  // ---- side schemes (v1.3) ----
  ritual_of_the_crown: {
    name: "Ritual of the Crown", type: "sidescheme", enter: 3, boost: 1,
    text: "Enters with 3 doom. While in play: the villain's ATTACK +1. Severed: draw 2 cards.",
    flavor: "The crown remembers how to be worn.",
    ongoing: "villainAtk1",
    clear: { draw: 2 },
  },
  harvest_of_souls: {
    name: "Harvest of Souls", type: "sidescheme", enter: 2, boost: 1,
    text: "Enters with 2 doom. While in play: minions' ATTACK +1. Severed: your hero heals 2.",
    flavor: "The city sleeps lighter every night.",
    ongoing: "minionAtk1",
    clear: { heal: 2 },
  },
  the_great_chant: {
    name: "The Great Chant", type: "sidescheme", enter: 3, boost: 2,
    text: "Enters with 3 doom. While in play: Doom spreads +1 each round. Severed: remove 2 doom from the main scheme.",
    flavor: "One voice is a prayer. Ten thousand are a verdict.",
    ongoing: "doomPlus1",
    clear: { mainThwart: 2 },
  },
  tithe_of_whispers: {
    name: "Tithe of Whispers", type: "sidescheme", enter: 2, boost: 1,
    text: "Enters with 2 doom. While in play: you refill your hand to 1 less. Severed: draw 2 cards.",
    flavor: "Every secret paid is a door unlocked.",
    ongoing: "handMinus1",
    clear: { draw: 2 },
  },
  // ---- the Court's arsenal (v1.9): villain upgrades & keyworded threats ----
  obsidian_ward: {
    name: "Obsidian Ward", type: "attachment", boost: 1,
    text: "Villain upgrade — the first damage the villain takes each round is reduced by 2. Shatters when his stage breaks.",
    flavor: "The dark learned to flinch.",
    trigger: { armor: 2 },
  },
  hungering_blade: {
    name: "Hungering Blade", type: "attachment", boost: 2,
    text: "Villain upgrade — when his ATTACK deals damage, he heals 2. Shatters when his stage breaks.",
    flavor: "It was forged hungry.",
    trigger: { lifesteal: 2 },
  },
  ash_revenant: {
    name: "Ash Revenant", type: "minion", atk: 2, hp: 3, boost: 1, tough: true, retaliate: 1,
    text: "TOUGH — ignores the first damage dealt to it. RETALIATE 1 — while it lives, whoever attacks it suffers 1 damage.",
    flavor: "It remembers every blade that failed.",
  },
  spire_shrike: {
    name: "Spire Shrike", type: "minion", atk: 1, hp: 1, boost: 1, quickstrike: true, surge: true,
    text: "Quickstrike — attacks immediately when it spawns. SURGE — reveal another encounter card.",
    flavor: "It arrives screaming, and never alone.",
  },
  the_court_convenes: {
    name: "The Court Convenes", type: "treachery", boost: 1, surge: true,
    text: "Place 1 doom. SURGE — reveal another encounter card.",
    flavor: "When the candles gutter, the verdicts multiply.",
    fx: { threat: 1 },
  },
  crowning_ritual: {
    name: "Crowning Ritual", type: "treachery", boost: 2,
    text: "If the villain has an upgrade attached: place 2 doom and he heals 2. Otherwise: place 1 doom.",
    flavor: "A crown is a promise the dark keeps.",
    fx: { crowning: true },
  },
  // ---- crisis side schemes (v1.7) — they shield the agenda ----
  rite_of_binding: {
    name: "Rite of Binding", type: "sidescheme", enter: 3, boost: 1, crisis: true,
    text: "CRISIS — while this is in play, doom cannot be removed from the agenda. Severed: draw 1 card.",
    flavor: "They chained the wound shut with your name.",
    clear: { draw: 1 },
  },
  veil_of_despair: {
    name: "Veil of Despair", type: "sidescheme", enter: 2, boost: 2, crisis: true,
    text: "CRISIS — while this is in play, doom cannot be removed from the agenda. Severed: your hero heals 2.",
    flavor: "Grief settles like ash. It does not melt.",
    clear: { heal: 2 },
  },
};

// intentPattern: "alternate" = attack on odd rounds; "thirdBell" = attack every 3rd round
export const VILLAINS = {
  morvane: {
    id: "morvane",
    name: "Morvane",
    art: "villain_morvane",
    epithet: "The Hollow King",
    hint: "Alternates ATTACK and SCHEME. Hits like a falling crown.",
    intentPattern: "alternate",
    agenda: {
      name: "The Hollowing",
      art: "scheme_hollowing",
      stages: [
        { name: "Whispers in the Walls", th: { normal: 9, nightmare: 7 },
          text: "The city forgets itself, one name at a time." },
        { name: "The Veil Descends", th: { normal: 9, nightmare: 8 },
          text: "Advance: Morvane heals 3. While here: his ATTACK +1.",
          onAdvance: { healVillain: 3 }, ongoing: { atk: 1 } },
        { name: "A Crown of Hollow Names", th: { normal: 10, nightmare: 8 },
          text: "Advance: a Void Cultist spawns and a card is torn from your hand. While here: his SCHEME +1. If this fills — Ashenmoor is lost.",
          onAdvance: { spawn: "void_cultist", discardRandom: 1 }, ongoing: { sch: 1 } },
      ],
    },
    stages: [
      { title: "Morvane, the Veiled",  hp: 12, atk: 2, sch: 1 },
      { title: "Morvane, Unbound",     hp: 14, atk: 3, sch: 2, onReveal: { spawn: "void_cultist" } },
      { title: "The Hollow King",      hp: 16, atk: 4, sch: 2, onReveal: { threat: 2 } },
    ],
    encDeck: [
      "void_cultist", "void_cultist", "void_cultist",
      "hollow_beast", "hollow_beast",
      "rift_stalker", "rift_stalker",
      "creeping_despair", "creeping_despair", "creeping_despair",
      "void_lash", "void_lash",
      "shattered_nerves", "shattered_nerves",
      "feast_of_shadows", "feast_of_shadows",
      "whispers_of_the_spire", "whispers_of_the_spire",
      "crown_of_echoes",
      "void_edge",
      "ritual_of_the_crown",
      "harvest_of_souls",
      "rite_of_binding",
      "obsidian_ward",
      "ash_revenant",
      "the_court_convenes",
    ],
  },
  vexahl: {
    id: "vexahl",
    name: "Vexahl",
    art: "hero_vexahl",
    epithet: "Voice of the Spire",
    hint: "Schemes relentlessly — strikes on every third bell.",
    intentPattern: "thirdBell",
    agenda: {
      name: "The Toll of Bells",
      art: "scheme_vexahl",
      stages: [
        { name: "The First Toll", th: { normal: 11, nightmare: 9 },
          text: "Somewhere below the water, a bell answers." },
        { name: "The Chorus Swells", th: { normal: 11, nightmare: 9 },
          text: "Advance: a Void Cultist spawns to sing. While here: minions' ATTACK +1.",
          onAdvance: { spawn: "void_cultist" }, ongoing: { minionAtk: 1 } },
        { name: "The Final Proclamation", th: { normal: 12, nightmare: 10 },
          text: "Advance: the verdict lands — 1 doom at once. While here: Doom spreads +1 each round. If this fills — Ashenmoor is lost.",
          onAdvance: { doom: 1 }, ongoing: { doomPerRound: 1 } },
      ],
    },
    stages: [
      { title: "Vexahl, the Whisper",      hp: 11, atk: 2, sch: 2 },
      { title: "Vexahl, the Chorus",       hp: 13, atk: 2, sch: 3, onReveal: { threat: 2 } },
      { title: "Vexahl, the Proclamation", hp: 15, atk: 3, sch: 3, onReveal: { spawn: "rift_stalker" } },
    ],
    encDeck: [
      "void_cultist", "void_cultist", "void_cultist",
      "hollow_beast", "hollow_beast",
      "rift_stalker", "rift_stalker",
      "creeping_despair", "creeping_despair", "creeping_despair",
      "shattered_nerves", "shattered_nerves",
      "chant_of_hollowing", "chant_of_hollowing",
      "silvered_tongue", "silvered_tongue",
      "herald_of_the_spire", "herald_of_the_spire",
      "crown_of_echoes",
      "void_edge",
      "the_great_chant",
      "tithe_of_whispers",
      "veil_of_despair",
      "hungering_blade",
      "spire_shrike",
      "the_court_convenes",
    ],
  },
  nul: {
    id: "nul",
    name: "Nul",
    art: "hero_nul",
    epithet: "The Spire-Heart",
    hint: "The source of it all. Everything, at once, faster.",
    intentPattern: "alternate",
    agenda: {
      name: "The Spire Consumes",
      art: "scheme_nul",
      stages: [
        { name: "Roots Beneath the City", th: { normal: 10, nightmare: 8 },
          text: "Every cellar in Ashenmoor grows the same black stone." },
        { name: "The Feeding", th: { normal: 10, nightmare: 8 },
          text: "Advance: the Spire drinks — you take 2 damage and Nul heals 3. While here: minions' ATTACK +1.",
          onAdvance: { directDmg: 2, healVillain: 3 }, ongoing: { minionAtk: 1 } },
        { name: "Ascension", th: { normal: 11, nightmare: 9 },
          text: "Advance: a Rift Stalker tears through. While here: his SCHEME +1. If this fills — Ashenmoor is lost.",
          onAdvance: { spawn: "rift_stalker" }, ongoing: { sch: 1 } },
      ],
    },
    stages: [
      { title: "The Heartbeat",       hp: 14, atk: 3, sch: 2 },
      { title: "The Waking Spire",    hp: 16, atk: 3, sch: 3, onReveal: { spawn: "rift_stalker" } },
      { title: "Nul, the Spire-Heart", hp: 18, atk: 4, sch: 3, onReveal: { threat: 3 } },
    ],
    encDeck: [
      "void_cultist", "void_cultist",
      "hollow_beast", "hollow_beast",
      "rift_stalker", "rift_stalker",
      "herald_of_the_spire", "herald_of_the_spire",
      "creeping_despair", "creeping_despair",
      "void_lash", "void_lash",
      "shattered_nerves", "shattered_nerves",
      "chant_of_hollowing", "chant_of_hollowing",
      "silvered_tongue",
      "whispers_of_the_spire",
      "crown_of_echoes",
      "void_edge",
      "ritual_of_the_crown",
      "the_great_chant",
      "rite_of_binding",
      "veil_of_despair",
      "obsidian_ward",
      "hungering_blade",
      "ash_revenant",
      "spire_shrike",
      "crowning_ritual",
    ],
  },
};
