// Every player-visible UI string lives here (card data text lives in js/cards.js,
// which is also data). Swap this module to localize the interface.
export const STR = {
  title: "ASHENMOOR",
  subtitle: "A solo card game of the Hollow King",
  menu: {
    newGame: "New Game",
    continue: "Continue",
    howToPlay: "How to Play",
    chooseWarden: "Choose your Warden",
    chooseVillain: "Choose your Nightmare",
    wins: "Vigils won",
    difficulty: "Difficulty",
    normal: "Normal",
    nightmare: "Nightmare",
    nightmareHint: "Nightmare: the Hollow King has more health and the Hollowing needs less doom.",
    start: "Begin the Vigil",
    mute: "Sound",
    version: "v1.4 · The Long Vigil",
  },
  coop: {
    title: "TWIN VIGILS",
    subtitle: "Two Wardens. One Nightmare. Linked fates.",
    connecting: "Reaching across the Void…",
    waiting: "Waiting for your partner — send them this link:",
    pickHero: "Choose your Warden — the vigil begins when both stand ready",
    partner: "Partner",
    partnerJoined: "Your partner stands watch. Fight!",
    beacon: "Send Beacon",
    beaconSpent: "Beacon spent",
    aidReceived: "Your partner's beacon reaches you: +2 shield, +1 card!",
    beaconSent: "Your beacon streaks across the Void.",
    youFell: "You have fallen. The vigil trembles…",
    held: "Your vigil holds — your partner still fights. Watch. Hope.",
    finalWinTitle: "THE TWIN VIGIL HOLDS",
    finalWinText: "Two Wardens, one storm, and the Nightmare broken twice over. Ashenmoor owes a double debt.",
    finalLoseTitle: "THE VIGIL BREAKS",
    finalLoseText: "A Warden has fallen, and a vigil of two cannot be held by one. The Void closes the ledger.",
    again: "Light the candles again",
    disconnected: "Disconnected — reconnecting…",
    spectating: "The room is full — you are watching.",
    sameStorm: "You both face {v} — the same nightmare, card for card.",
  },
  campaign: {
    title: "The Long Vigil",
    subtitle: "Three Nightmares. One Warden. Every wound remembered.",
    menuNew: "The Long Vigil — Campaign",
    menuContinue: "Continue the Vigil (Act {n})",
    act: "Act",
    done: "CAST DOWN",
    current: "THE VIGIL STANDS HERE",
    locked: "SEALED",
    begin: "Begin Act {n}",
    viewDeck: "View Deck ({n})",
    abandon: "Abandon the Vigil",
    back: "Back",
    scars: "Scars: -{n} max health",
    doomCarried: "The city burns: next act begins with {n} doom",
    draftTitle: "Spoils of the Vigil",
    draftText: "Choose one card to add to your deck.",
    removeTitle: "Lighten the burden",
    removeText: "You may remove one card from your deck (optional).",
    skip: "Keep everything",
    continueVigil: "Continue the Vigil",
    retryScar: "Rise again — bear a scar (-1 max health)",
    epWinTitle: "THE VIGIL ENDS",
    epWinText: "Morvane. Vexahl. Nul. All cast down. Ashenmoor wakes to its first honest dawn in a hundred years — and the Warden who held the long watch wears an invisible crown.",
    epFailTitle: "THE WATCH FAILS",
    epFailText: "Too many scars. The Warden's body gives out before the Spire's heart does, and Ashenmoor fades quietly into the Void's ledger.",
    crowned: "Crowned",
    deckLabel: "cards in deck",
    newRun: "A new Vigil",
  },
  hud: {
    round: "Round",
    intent: "Intent",
    intentAttack: "ATTACK",
    intentScheme: "SCHEME",
    intentSealed: "SEALED",
    intentStunned: "STUNNED",
    endTurn: "End Turn",
    deck: "Deck",
    discard: "Discard",
    encounterDeck: "Encounter",
    threat: "Doom",
    stage: "Stage",
    hp: "Health",
    shield: "Shield",
    log: "Chronicle",
    help: "Rules",
    menu: "Menu",
    restart: "Restart",
    exhausted: "Exhausted",
  },
  actions: {
    play: "Play",
    attack: "Attack",
    thwart: "Disrupt",
    ability: "Ability",
    confirm: "Confirm",
    cancel: "Cancel",
    auto: "Auto",
    keepHand: "Keep hand",
    mulligan: "Redraw selected",
    payPrompt: "Pay {n}: select cards to discard",
    paySelected: "{sum} / {n} paid",
    chooseTarget: "Choose a target",
    resourceOnly: "Resource — can only be spent to pay costs.",
    allyLimit: "You can control at most 3 allies.",
    needMinion: "No minion in play.",
    cannotAfford: "Not enough cards to pay for this.",
    heroExhausted: "Your hero is exhausted.",
    abilityUsed: "Ability already used this round.",
  },
  defense: {
    title: "{attacker} attacks for {dmg}!",
    take: "Take it ({dmg} damage)",
    heroDefend: "Defend with hero ({dmg} damage)",
    allyBlock: "Block with {name}",
    allyDies: "will be destroyed",
    boostNote: "A boost card lurks — the attack may hit harder than shown (◆).",
  },
  mulligan: {
    title: "Opening hand",
    text: "Select any cards to shuffle back and redraw (once).",
  },
  phases: {
    villainPhase: "Villain Phase",
    doom: "Doom spreads...",
    yourTurn: "Your turn",
  },
  end: {
    victory: "VICTORY",
    defeat: "DEFEAT",
    winReason: "The Nightmare is cast down. Ashenmoor breathes again.",
    loseHp: "Your Warden has fallen.",
    loseScheme: "The Hollowing is complete. The city fades into the Void.",
    rounds: "Rounds survived",
    dmg: "Damage dealt",
    threat: "Doom dispelled",
    cards: "Cards played",
    again: "Play Again",
  },
  help: {
    title: "How to Play",
    close: "Close",
    body: [
      ["Goal", "Defeat all three stages of the villain before the main scheme fills with doom twice — and before your Warden falls."],
      ["Your turn", "Play cards from your hand. A card's cost (top-left gem) is paid by discarding OTHER cards from your hand — most cards are worth 1 while paying, Warden's Resolve is worth 2. Your hero can also act once per turn: Attack an enemy or Disrupt (remove doom from the scheme). If your hero has not acted, they may defend later."],
      ["Allies & upgrades", "Allies (max 3) can Attack or Disrupt once per round, then suffer 1 damage. Upgrades stay in play and improve your hero."],
      ["Villain phase", "Doom grows by 1. The villain then acts on its telegraphed intent — ATTACK or SCHEME (+doom). Each villain has a rhythm: Morvane alternates every round; Vexahl schemes and strikes only on every third bell. Each minion attacks. Finally a new encounter card is revealed. When attacked, you choose: take the damage, defend with your ready hero (reduced by DEF), or block with a ready ally (the ally takes it all)."],
      ["Hero ability", "Each Warden has a free ability, once per round — Kaelen deals 1 damage; Sera removes 1 doom; Odran gains 1 shield."],
      ["Stages", "When a villain stage is defeated, a stronger one rises. If the scheme's doom track fills, it advances — the second time, you lose. When your deck runs out it reshuffles and adds 1 doom."],
      ["Side schemes", "Some encounter cards take root beside the main scheme with their own doom (◆) and a nasty ongoing effect. Your Disrupt now chooses its target — sever a side scheme (reduce it to 0) to end its effect and claim a reward."],
      ["Guard, Boost & statuses", "GUARD minions must be slain before the villain can be attacked. When the villain attacks, he secretly draws a boost card and adds its ◆ value to the hit — defend with that risk in mind. Stun makes the villain skip his next ATTACK; Burn sears him for 1 at the start of each villain phase until it fades."],
      ["Tips", "Every card is also fuel. Holding a ready ally as a blocker often saves your hero. Watch the intent: on SCHEME rounds you can attack freely; before ATTACK rounds, keep a defender ready."],
    ],
  },
  hints: {
    firstHand: "Tap a card, then Play. You pay its cost by discarding other cards.",
    endTurn: "When you are done, press End Turn — the Hollow King acts next.",
  },
  log: {
    gameStart: "The vigil begins. {hero} stands against {villain}.",
    doom: "Doom spreads (+{n}).",
    schemeAdvance: "The Hollowing advances! {v} grows stronger (+1 ATK, heals 3).",
    stageDown: "{stage} is defeated!",
    stageUp: "{stage} rises — {hp} health.",
    villainAttack: "{v} attacks for {n}.",
    villainScheme: "{v} schemes (+{n} doom).",
    villainSealed: "Time slips — the villain does not act.",
    minionAttack: "{m} attacks for {n}.",
    minionSpawn: "{m} joins the Hollow Court.",
    minionCrowded: "The Hollow Court is full — despair grows (+2 doom).",
    treachery: "Treachery: {t}.",
    attachment: "{t} empowers the villain.",
    reveal: "Encounter: {t}.",
    heroDefend: "{hero} defends ({n} damage after armor).",
    allyBlock: "{ally} blocks the attack.",
    allyDown: "{ally} is destroyed.",
    take: "{hero} suffers {n} damage.",
    shieldAbsorb: "Shield absorbs {n}.",
    playCard: "{hero} plays {c}.",
    payed: "(paid with {cards})",
    basicAttack: "{who} attacks {t} for {n}.",
    basicThwart: "{who} disrupts the scheme (-{n} doom).",
    abilityKaelen: "Emberheart burns {t} for 1.",
    abilitySera: "Riftsight unravels 1 doom.",
    abilityOdran: "Aegis hardens (+1 shield).",
    rally: "The Watch stands ready!",
    silvered: "{ally} is beguiled and exhausts.",
    sideSpawn: "{t} takes root — {n} doom to sever it.",
    sideClear: "{t} is severed!",
    sideCrowded: "The schemes overflow (+2 doom).",
    stunned: "{v} is stunned and reels — the attack falters!",
    stunApplied: "{v} is Stunned!",
    burnApplied: "Cinders brand {v} (Burn {n}).",
    burnTick: "Cinders sear {v} (1 damage).",
    boost: "Boost: {t} (+{n} ATK).",
    draw: "Draws {n} card(s).",
    reshuffle: "The deck is reshuffled — the Void stirs (+1 doom).",
    discardRandom: "{c} is torn from your hand.",
    heal: "{hero} heals {n}.",
    healVillain: "{v} feasts and heals {n}.",
    exhaustHero: "Whispers exhaust your hero.",
    win: "The Nightmare falls. Victory!",
    loseHp: "Your Warden falls. Defeat.",
    loseScheme: "The Hollowing is complete. Defeat.",
    mulligan: "Redraws {n} card(s).",
    quickstrike: "Quickstrike!",
  },
};
