// Every player-visible UI string lives here (card data text lives in js/cards.js,
// which is also data). Swap this module to localize the interface.
export const STR = {
  title: "ASHENMOOR",
  subtitle: "A solo card game of the Hollow King",
  menu: {
    newGame: "New Game",
    continue: "Continue",
    howToPlay: "How to Play",
    chooseWarden: "Choose your Warden",
    chooseVillain: "Choose your Nightmare",
    wins: "Vigils won",
    difficulty: "Difficulty",
    normal: "Normal",
    nightmare: "Nightmare",
    nightmareHint: "Nightmare: the villain has more health and his agenda needs less doom per stage.",
    start: "Begin the Vigil",
    daily: "Daily Vigil",
    stats: "Statistics",
    firstVigil: "Choose a Warden and Nightmare below, or begin immediately with the highlighted pair.",
    mute: "Sound",
    version: "v2.3 · Foresight",
  },
  coop: {
    title: "TWIN VIGILS",
    subtitle: "Two Wardens. One Nightmare. Linked fates.",
    connecting: "Reaching across the Void…",
    waiting: "Waiting for your partner — send them this link:",
    pickHero: "Choose your Warden — the vigil begins when both stand ready",
    partner: "Partner",
    partnerJoined: "Your partner stands watch. Fight!",
    beacon: "Send Beacon",
    beaconSpent: "Beacon spent",
    aidReceived: "Your partner's beacon reaches you: +2 shield, +1 card!",
    beaconSent: "Your beacon streaks across the Void.",
    youFell: "You have fallen. The vigil trembles…",
    held: "Your vigil holds — your partner still fights. Watch. Hope.",
    finalWinTitle: "THE TWIN VIGIL HOLDS",
    finalWinText: "Two Wardens, one storm, and the Nightmare broken twice over. Ashenmoor owes a double debt.",
    finalLoseTitle: "THE VIGIL BREAKS",
    finalLoseText: "A Warden has fallen, and a vigil of two cannot be held by one. The Void closes the ledger.",
    again: "Light the candles again",
    disconnected: "Disconnected — reconnecting…",
    spectating: "The room is full — you are watching.",
    sameStorm: "You both face {v} — the same nightmare, card for card.",
  },
  campaign: {
    title: "The Long Vigil",
    subtitle: "Three Nightmares. One Warden. Every wound remembered.",
    menuNew: "The Long Vigil — Campaign",
    menuContinue: "Continue the Vigil (Act {n})",
    act: "Act",
    done: "CAST DOWN",
    current: "THE VIGIL STANDS HERE",
    locked: "SEALED",
    begin: "Begin Act {n}",
    viewDeck: "View Deck ({n})",
    abandon: "Abandon the Vigil",
    back: "Back",
    scars: "Scars: -{n} max health",
    doomCarried: "The city burns: next act begins with {n} doom",
    resolve: "Rising resolve: next attempt begins with +{n} shield and +{n} card",
    draftTitle: "Spoils of the Vigil",
    draftText: "Choose one card to add to your deck.",
    removeTitle: "Lighten the burden",
    removeText: "You may remove one card from your deck (optional).",
    skip: "Keep everything",
    continueVigil: "Continue the Vigil",
    retryScar: "Regroup & retry",
    epWinTitle: "THE VIGIL ENDS",
    epWinText: "Morvane. Vexahl. Nul. All cast down. Ashenmoor wakes to its first honest dawn in a hundred years — and the Warden who held the long watch wears an invisible crown.",
    epFailTitle: "THE WATCH FAILS",
    epFailText: "Too many scars. The Warden's body gives out before the Spire's heart does, and Ashenmoor fades quietly into the Void's ledger.",
    crowned: "Crowned",
    deckLabel: "cards in deck",
    newRun: "A new Vigil",
  },
  hud: {
    round: "Round",
    intent: "Intent",
    intentAttack: "ATTACK",
    intentScheme: "SCHEME",
    intentSealed: "SEALED",
    intentStunned: "STUNNED",
    endTurn: "End Turn",
    deck: "Deck",
    discard: "Discard",
    encounterDeck: "Encounter",
    threat: "Doom",
    stage: "Stage",
    hp: "Health",
    shield: "Shield",
    log: "Chronicle",
    help: "Rules",
    menu: "Menu",
    restart: "Restart",
    exhausted: "Exhausted",
  },
  doomForecast: {
    next: "NEXT +{n}",
    advance: "ADVANCE +{n}",
    defeat: "DEFEAT +{n}",
    resolving: "RESOLVING",
    spread: "+{n} Spread",
    scheme: "+{n} Scheme",
    effects: "+{n} Effects",
    scheduled: "Next villain phase has +{n} known Doom before the encounter:",
    advances: "This will advance the agenda unless you remove enough Doom.",
    lethal: "This will complete the final agenda unless you remove enough Doom.",
    extra: "The hidden encounter card can still add more.",
    resolvingDetail: "The villain phase is resolving; NEXT returns on your turn.",
    carry: "Overflow carries into the next agenda stage. The hidden encounter card is not included in the forecast.",
  },
  actions: {
    play: "Play",
    attack: "Attack",
    thwart: "Disrupt",
    ability: "Ability",
    confirm: "Confirm",
    cancel: "Cancel",
    auto: "Auto",
    keepHand: "Keep hand",
    mulligan: "Redraw selected",
    payPrompt: "Pay {n}: select cards to discard",
    paySelected: "{sum} / {n} paid",
    chooseTarget: "Choose a target",
    resourceOnly: "Resource — can only be spent to pay costs.",
    allyLimit: "You can control at most 3 allies.",
    needMinion: "No minion in play.",
    cannotAfford: "Not enough cards to pay for this.",
    heroExhausted: "Your hero is exhausted.",
    abilityUsed: "Ability already used this round.",
    crisisBlock: "A CRISIS scheme shields the agenda — sever it first!",
  },
  defense: {
    title: "{attacker} attacks for {dmg}!",
    take: "Take it ({dmg} damage)",
    heroDefend: "Defend with hero ({dmg} damage)",
    allyBlock: "Block with {name}",
    allyDies: "will be destroyed",
    boostNote: "A boost card lurks — the attack may hit harder than shown (◆).",
  },
  mulligan: {
    title: "Opening hand",
    text: "Select any cards to shuffle back and redraw (once).",
  },
  phases: {
    villainPhase: "Villain Phase",
    doom: "Doom spreads...",
    yourTurn: "Your turn",
  },
  end: {
    victory: "VICTORY",
    defeat: "DEFEAT",
    winReason: "The Nightmare is cast down. Ashenmoor breathes again.",
    loseHp: "Your Warden has fallen.",
    loseScheme: "The agenda is complete. The city fades into the Void.",
    rounds: "Rounds survived",
    dmg: "Damage dealt",
    threat: "Doom dispelled",
    cards: "Cards played",
    again: "Play Again",
  },
  help: {
    title: "How to Play",
    close: "Close",
    goal: "Defeat all three stages of the villain before his agenda completes all three of its stages — and before your Warden falls.",
    flowTitle: "Your turn — in any order",
    flow: [
      "Play cards from your hand. Pay a card's cost (the gold gem) by discarding OTHER cards from your hand — every card is worth 1 while paying; Warden's Resolve is worth 2, Shard of the Spire 3. Cards you can afford glow gold.",
      "Use your hero once: ⚔ Attack an enemy OR ✧ Disrupt (remove doom from a scheme). A hero who has NOT acted stays ready to defend in the villain phase.",
      "Use your hero's ✦ ability — free, once per round (Kaelen burns for 1; Sera removes 1 doom; Odran gains 1 shield).",
      "Order your allies: each may ⚔ attack or ✧ disrupt once per round (the small buttons under the ally), then suffers 1 damage.",
      "Press End Turn when you are done — the villain acts next.",
    ],
    vpTitle: "Villain phase — the exact procedure",
    vpNote: "Each step is announced on screen, and a full recap panel appears before your next turn so nothing slips past you.",
    vp: [
      "🔥 Burn ticks (the villain takes 1 damage per Burn), then doom spreads: +1 on the agenda (more while The Great Chant or a late agenda stage is active). The agenda's NEXT forecast shows this before you end your turn.",
      "The villain acts on his telegraphed INTENT (shown at the top): ATTACK — he secretly draws a ◆ boost card for extra damage and you choose how to defend; or SCHEME — he adds his SCH value in doom. ⚡ Stun makes him skip an ATTACK.",
      "Every minion attacks, one by one. You choose a defender for each attack.",
      "One new encounter card is revealed: a minion spawns, a treachery resolves, an attachment empowers the villain, or a side scheme takes root.",
      "Cleanup: everyone readies, shields fade, you draw back up to hand size — then the recap shows everything that just happened.",
    ],
    anatomyTitle: "Reading a card",
    anatomy: [
      "Gold gem = cost. Pay it by discarding that many resources' worth of OTHER cards from your hand.",
      "Teal gem = a resource card: it cannot be played, but is worth extra when paying costs.",
      "Type line: EVENT — one-shot effect; ALLY — stays in play and acts each round; UPGRADE — permanent improvement; RESOURCE — only for paying.",
      "◆ diamonds in the corner of encounter cards = hidden Boost damage if that card is drawn during a villain attack.",
      "Stats: ⚔ attack · ✧ disrupt · 🛡 defense · ♥ health.",
    ],
    legendTitle: "Symbols & keywords",
    legend: [
      ["⚔", "Attack", "Damage dealt by a basic attack (hero or ally). Exhausts the attacker."],
      ["✧", "Disrupt", "Doom removed from a scheme by a basic disrupt. Exhausts the user."],
      ["🛡", "DEF / Shield", "DEF reduces damage when your hero defends. Shield absorbs any damage first and fades at the start of your turn."],
      ["♥", "Health", "When your hero's reaches 0, you lose. Allies and minions die at 0."],
      ["✦", "Ability", "Your hero's free power — once per round (The Warden's Oath makes it twice)."],
      ["◆", "Doom / Boost", "On schemes: doom left to clear. On encounter cards: hidden bonus damage for villain attacks."],
      ["⚡", "Stun", "The villain skips his next ATTACK activation."],
      ["🔥", "Burn", "The villain takes 1 damage at the start of each villain phase, then 1 Burn fades."],
      ["GUARD", "Guard", "While this minion lives, the villain cannot be attacked or targeted by your damage."],
      ["QUICK", "Quickstrike", "This minion attacks immediately when it spawns."],
      ["SEALED", "Sealed", "Temporal Slip: the villain skips his whole activation this round."],
      ["🔒", "Crisis", "While this side scheme is in play, no doom can be removed from the agenda. Sever it first."],
      ["⚡", "Surge", "When this encounter card resolves, reveal another encounter card immediately."],
      ["🗿", "Tough", "This minion ignores the first damage dealt to it — you must hit it twice."],
      ["🩸", "Retaliate", "While this minion lives, whoever attacks it takes damage back."],
      ["💀", "Haunt", "When this minion dies — by any means — its printed death effect triggers. Time your kills."],
      ["💥", "Burst", "Side schemes grow every second villain phase. If one fills to its printed burst number, it detonates with a nasty effect and discards itself — no sever reward."],
      ["👑", "Signature", "Each villain has a signature keyword shown on his card: Morvane OVERWHELM (1 excess damage through dead blockers), Vexahl RESONANT (side schemes enter with +1 doom), Nul SURGING (boosts never less than ◆1), Oszra MOURNFUL (first minion death each round feeds her side schemes)."],
      ["⛨", "Villain upgrade", "An attachment that works every round (armor, lifesteal...). All upgrades shatter when the villain's stage breaks."],
    ],
    moreTitle: "Deeper rules",
    body: [
      ["Defending", "When attacked you choose: TAKE IT — full damage to your hero (shield absorbs first); DEFEND — your ready hero exhausts and the damage is reduced by 🛡 DEF; or BLOCK — a ready ally takes ALL of it (usually dying heroically)."],
      ["Side schemes", "They take root beside the agenda with their own ◆ doom and a vicious ongoing effect — and they GROW every second villain phase. Sever one (reduce it to 0) to end its effect and claim its printed reward; let it fill to its burst number and it DETONATES instead, with no reward."],
      ["The agenda", "Each villain pursues his own three-stage agenda. NEXT simulates all known Doom before the hidden encounter: Spread, a telegraphed SCHEME, agenda advances, and visible side-scheme bursts. When the track fills, the agenda advances and the new stage's twist stays active. Doom past the threshold CARRIES OVER. If stage 3 fills, Ashenmoor falls."],
      ["Crisis schemes", "Side schemes marked 🔒 CRISIS shield the agenda: while one is in play, no doom can be removed from the agenda by anything. Sever the crisis first."],
      ["Deck limits", "Max 3 allies in play; a 4th minion can't spawn — it becomes +2 doom instead. When your deck runs out it reshuffles and adds 1 doom, so don't stall."],
      ["The Long Vigil (campaign)", "Three acts, one Warden, one growing deck. Win an act: draft 1 of 3 cards and optionally remove one. Barely surviving (≤2 ♥) scars you (-1 max ♥ for the whole campaign); a burning city carries 1 doom into the next act. Your first defeat in the campaign leaves no scar, and every defeat builds Resolve for the next attempt. Fall below 6 max ♥ and the Vigil fails."],
      ["Tips", "Every card is also fuel — a dead card in hand is 1 resource. Keep a blocker ready before ATTACK rounds; unload freely on SCHEME rounds. Sever side schemes early: their ongoing effects compound fast."],
    ],
  },
  tips: {
    attack: "Exhaust your hero to deal their ⚔ value in damage to an enemy. GUARD minions must die first. Once per round unless readied again.",
    disrupt: "Exhaust your hero to remove their ✧ value in doom from the main scheme or a side scheme.",
    endTurn: "End your turn. Villain phase follows: burn & doom, the villain acts on his intent, minions attack, a new encounter card is revealed — then you get a full recap.",
    allyAttack: "This ally attacks an enemy for its ⚔ value, then suffers 1 damage.",
    allyThwart: "This ally removes its ✧ value in doom from a scheme, then suffers 1 damage.",
    intent: "What the villain will do next villain phase. ATTACK = damage your side (+? is a hidden boost card). SCHEME = add doom. Plan your defense around it!",
    doom: "The villain's agenda. NEXT projects all known Doom before the hidden encounter, including Spread, SCHEME, agenda advances, and visible bursts. A full track advances, overflow carries over, and filling stage 3 loses the game.",
    crisis: "CRISIS — while this side scheme is in play, no doom can be removed from the agenda. Sever it first!",
    burst: "This side scheme grows every second villain phase. If it fills to this number it DETONATES with its printed effect — and you get no sever reward.",
    stunChip: "Stunned — the villain skips his next ATTACK activation (forced attacks included).",
    burnChip: "Burning — he takes 1 damage at the start of each villain phase, then 1 Burn fades.",
    agendaOngoing: "Lasting twist of the CURRENT agenda stage — active until the agenda advances again.",
    deck: "Your deck. When it empties, it reshuffles and adds 1 doom.",
    discard: "Discard pile — click to browse it.",
    encDeck: "The encounter deck — villain phase reveals and attack boosts are drawn from here.",
  },
  vp: {
    recapTitle: "The Villain's Move — recap",
    begin: "Begin your turn",
  },
  pause: {
    title: "Paused",
    resume: "Resume",
    howto: "How to Play",
    restart: "Restart this game",
    mainMenu: "Save & Main Menu",
    settings: "Settings",
  },
  settings: {
    title: "Settings",
    music: "Music & ambience",
    sfx: "Sound effects",
    speed: "Villain phase speed",
    slow: "Slow",
    normalSpeed: "Normal",
    fast: "Fast",
    effects: "Visual effects",
    full: "Full",
    reduced: "Reduced",
    shortcuts: "Shortcuts: E end turn · Enter confirm · Esc cancel · H help · M mute · F fullscreen",
  },
  confirm: {
    replaceTitle: "Replace the saved battle?",
    replaceText: "Starting this Vigil will discard the battle currently saved under Continue.",
    replace: "Start new Vigil",
    restartTitle: "Restart this Vigil?",
    restartText: "The current battle will be discarded and cannot be recovered.",
    restart: "Restart",
    abandonTitle: "Abandon the Long Vigil?",
    abandonText: "Campaign progress, deck changes, scars, and act history will be erased.",
    abandon: "Abandon campaign",
    cancel: "Keep playing",
  },
  coach: {
    title: "Your first watch",
    intro: "Four things are enough to begin. The full rules remain under ? or H.",
    steps: [
      "Select a card in your hand to inspect it; on touch screens the Play action appears in the bottom sheet.",
      "Pay a card's gold cost by discarding other cards. Every card is worth at least 1 resource.",
      "A ready Warden can defend during an ATTACK. Acting with the Warden exhausts that defense.",
      "Watch the intent at the top and remove doom before the agenda track fills.",
    ],
    go: "Stand the watch",
  },
  stats: {
    title: "Vigil Records",
    games: "Games",
    wins: "Wins",
    rate: "Win rate",
    avgRounds: "Avg. rounds",
    byWarden: "By Warden",
    recent: "Recent Vigils",
    none: "No completed Vigils yet.",
    win: "Victory",
    loss: "Defeat",
    daily: "Daily",
  },
  pile: {
    all: "All",
    search: "Search cards",
    empty: "No cards match this view.",
  },
  dock: {
    confirm: "Confirm & play (Enter)",
    auto: "Auto-select payment",
    cancel: "Cancel (Esc)",
    pool: "Your hand is your mana — this is its total value if spent as payment.",
  },
  reveal: {
    title: "Encounter revealed!",
    resolve: "Resolve it",
    minion: "A minion — it spawns now and will attack every villain phase until slain.",
    treachery: "A treachery — read it: its effect resolves right now, then it is discarded.",
    attachment: "An attachment — it latches onto the villain and empowers him permanently.",
    sidescheme: "A side scheme — it takes root with its own ◆ doom and an ongoing effect. It GROWS every second villain phase, and if it fills to its burst number it DETONATES. Sever it to 0 first!",
    quick: "⚡ Quickstrike — it will attack you immediately!",
    guard: "🛡 GUARD — the villain cannot be attacked while it lives.",
    crisis: "🔒 CRISIS — while it is in play, doom CANNOT be removed from the agenda. Sever this first!",
    surge: "⚡ SURGE — after this resolves, ANOTHER encounter card is revealed.",
    tough: "🗿 TOUGH — the first damage dealt to it is ignored entirely. Hit it twice.",
    retaliate: "🩸 RETALIATE {n} — while it lives, whoever attacks it suffers {n} damage back.",
    haunt: "💀 HAUNT — its DEATH triggers the printed effect. Sometimes it is better left alive.",
    upgrade: "It stays attached and works every round — but all upgrades SHATTER when you break the villain's stage.",
  },
  agenda: {
    title: "The Agenda Advances!",
    stageLabel: "Stage {n} of {total}",
    doomCarry: "Doom past the threshold carries over — the track does not reset.",
    face: "Face it",
  },
  hints: {
    endTurn: "When you are done, press End Turn — the Hollow King acts next.",
  },
  log: {
    gameStart: "The vigil begins. {hero} stands against {villain}.",
    doom: "Doom spreads (+{n}).",
    agendaAdvance: "{a} advances — {stage}!",
    agendaDirect: "The agenda feeds — {n} damage strikes you directly.",
    crisisBlock: "The CRISIS shields the agenda — no doom can be removed!",
    stageDown: "{stage} is defeated!",
    stageUp: "{stage} rises — {hp} health.",
    villainAttack: "{v} attacks for {n}.",
    villainScheme: "{v} schemes (+{n} doom).",
    villainSealed: "Time slips — the villain does not act.",
    minionAttack: "{m} attacks for {n}.",
    minionSpawn: "{m} joins the Hollow Court.",
    minionCrowded: "The Hollow Court is full — despair grows (+2 doom).",
    treachery: "Treachery: {t}.",
    attachment: "{t} empowers the villain.",
    reveal: "Encounter: {t}.",
    heroDefend: "{hero} defends ({n} damage after armor).",
    allyBlock: "{ally} blocks the attack.",
    allyDown: "{ally} is destroyed.",
    take: "{hero} suffers {n} damage.",
    shieldAbsorb: "Shield absorbs {n}.",
    playCard: "{hero} plays {c}.",
    payed: "(paid with {cards})",
    basicAttack: "{who} attacks {t} for {n}.",
    basicThwart: "{who} disrupts the scheme (-{n} doom).",
    abilityKaelen: "Emberheart burns {t} for 1.",
    abilitySera: "Riftsight unravels 1 doom.",
    abilityOdran: "Aegis hardens (+1 shield).",
    abilityIlva: "Wildcall mends the most wounded packmate (+2).",
    abilityIlvaAlone: "Wildcall circles home (+1 shield).",
    healAllies: "The pack mends ({n} each).",
    haunt: "HAUNT — {m}'s death springs its trap!",
    revive: "{m} claws back out of the grave!",
    sideBurst: "{t} BURSTS — its effect erupts!",
    resonant: "RESONANT — Vexahl's echo adds 1 doom.",
    mournful: "MOURNFUL — Oszra's grief feeds the scheme (+1).",
    overwhelm: "OVERWHELM — {n} damage crashes through to your hero!",
    rally: "The Watch stands ready!",
    silvered: "{ally} is beguiled and exhausts.",
    sideSpawn: "{t} takes root — {n} doom to sever it.",
    sideClear: "{t} is severed!",
    sideCrowded: "The schemes overflow (+2 doom).",
    stunned: "{v} is stunned and reels — the attack falters!",
    stunApplied: "{v} is Stunned!",
    burnApplied: "Cinders brand {v} (Burn {n}).",
    burnTick: "Cinders sear {v} (1 damage).",
    boost: "Boost: {t} (+{n} ATK).",
    draw: "Draws {n} card(s).",
    reshuffle: "The deck is reshuffled — the Void stirs (+1 doom).",
    discardRandom: "{c} is torn from your hand.",
    heal: "{hero} heals {n}.",
    healVillain: "{v} feasts and heals {n}.",
    exhaustHero: "Whispers exhaust your hero.",
    win: "The Nightmare falls. Victory!",
    loseHp: "Your Warden falls. Defeat.",
    loseScheme: "The agenda is complete. Defeat.",
    mulligan: "Redraws {n} card(s).",
    quickstrike: "Quickstrike!",
    surge: "SURGE — the Court piles on!",
    toughAbsorb: "{m} is TOUGH — the first blow glances off.",
    retaliate: "{m} RETALIATES for {n}!",
    armor: "The villain's ward soaks {n} damage.",
    attachShatter: "His upgrades shatter with his broken form!",
    lifesteal: "The Hungering Blade feeds — he heals {n}.",
  },
};
